on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
